use_frameworks!

platform :ios, '12.0'

target 'OnBoardingScanner_Example' do
  
  # Uncommet when implement and add your path of pod `OnBoardingScanner`
  # pod 'OnBoardingScanner', :path => '{Add your path file}'
  pod 'SnapKit', '~> 5.6.0'
  pod 'BSImagePicker', :git => 'https://dev.azure.com/sansiri-dev-ops/mws/_git/BSImagePicker'


  target 'OnBoardingScanner_Tests' do
    inherit! :search_paths
  end
  
  post_install do |installer|
        installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                end
            end
        end
    end
end
