use_frameworks!

platform :ios, '10.0'

target 'OnBoardingScanner_Example' do
  pod 'OnBoardingScanner', :path => '../'

  target 'OnBoardingScanner_Tests' do
    inherit! :search_paths

    
  end
end
