//
//  QRScannerRouter.swift
//  Pods
//
//  Created by NB1003917 on 28/2/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol QRScannerRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol QRScannerDataPassing {
    var dataStore: QRScannerDataStore? { get }
}

class QRScannerRouter: NSObject, QRScannerRoutingLogic, QRScannerDataPassing {
    
    weak var viewController: QRScannerViewController?
    var dataStore: QRScannerDataStore?
}
