//
//  QRScannerInteractor.swift
//  Pods
//
//  Created by NB1003917 on 28/2/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol QRScannerBusinessLogic {
    func doSomething(request: QRScanner.Something.Request)
}

protocol QRScannerDataStore {
    //var name: String { get set }
}

class QRScannerInteractor: QRScannerBusinessLogic, QRScannerDataStore {
    var presenter: QRScannerPresentationLogic?
    var worker: QRScannerWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: QRScanner.Something.Request) {
        worker = QRScannerWorker()
        worker?.doSomeWork()
        
        let response = QRScanner.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
