//
//  OnBoardingScannerPresenter.swift
//  Pods
//
//  Created by NB1003917 on 28/2/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnBoardingScannerPresentationLogic {
    func presentSomething(response: OnBoardingScanner.Something.Response)
}

class OnBoardingScannerPresenter: OnBoardingScannerPresentationLogic {
    
    weak var viewController: OnBoardingScannerDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: OnBoardingScanner.Something.Response) {
        let viewModel = OnBoardingScanner.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
