//
//  OnBoardingScannerRouter.swift
//  Pods
//
//  Created by NB1003917 on 28/2/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol OnBoardingScannerRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol OnBoardingScannerDataPassing {
    var dataStore: OnBoardingScannerDataStore? { get }
}

class OnBoardingScannerRouter: NSObject, OnBoardingScannerRoutingLogic, OnBoardingScannerDataPassing {
    
    weak var viewController: OnBoardingScannerViewController?
    var dataStore: OnBoardingScannerDataStore?
}
