//
//  OnBoardingScannerInteractor.swift
//  Pods
//
//  Created by NB1003917 on 28/2/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnBoardingScannerBusinessLogic {
    func doSomething(request: OnBoardingScanner.Something.Request)
}

protocol OnBoardingScannerDataStore {
    //var name: String { get set }
}

class OnBoardingScannerInteractor: OnBoardingScannerBusinessLogic, OnBoardingScannerDataStore {
    var presenter: OnBoardingScannerPresentationLogic?
    var worker: OnBoardingScannerWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: OnBoardingScanner.Something.Request) {
        worker = OnBoardingScannerWorker()
        worker?.doSomeWork()
        
        let response = OnBoardingScanner.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
